# Generated by Django 3.2.21 on 2023-10-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blood_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phonno', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('phonno', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('BLOOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.blood_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.CharField(max_length=300)),
                ('details', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.hospital_table')),
            ],
        ),
        migrations.AddField(
            model_name='hospital_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.login_table'),
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.hospital_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=300)),
                ('replay', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.hospital_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.user_table')),
            ],
        ),
    ]
