# Generated by Django 3.2.21 on 2024-01-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_blood_bank_table_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='USER',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blood.user_table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request_table',
            name='blood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.blood_table'),
        ),
    ]
