# Generated by Django 3.2.21 on 2024-01-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_request_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='count',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
