# Generated by Django 3.2.21 on 2024-01-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_request_table_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='response_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=300)),
                ('REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.request_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.user_table')),
            ],
        ),
    ]
