# Generated by Django 4.2.5 on 2024-03-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_response_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_table',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospital_table',
            name='longitude',
        ),
        migrations.AddField(
            model_name='hospital_table',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital_table',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
