# Generated by Django 4.2.5 on 2024-03-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_table',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
