# Generated by Django 4.2.5 on 2024-03-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_alter_blood_table_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_table',
            name='date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='feedback_table',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
